#!/bin/bash
###Checking on the other branch
#mobile
####....check cimtrak service presence....#####

agent=$(ps -ef | grep -v grep | grep CimTrakAgent)

if [[ $agent = *CimTrakAgent* ]]
then	
	cd /opt/Cimcor/CimTrak/CimTrakAgent/; echo 'password' | sudo -S ./CimTrakAgent.exe --restart &> /dev/null ;
	
	###agent is present on host###
	
else
	echo "Let us uninstall the agent now";
	if [ -d /opt/Cimcor/CimTrak/CimTrakAgent ]
	then
		echo "Let us remove the folder  now";
		echo '280816Ll' | sudo -S rm -rf /opt/Cimcor/CimTrak/CimTrakAgent/;
		echo "Let us uninstall too";
		cd / ; echo '*******' | sudo -S ./ctagent_e_setup_linux_x64_04010000_16954_20200514.run --mode unattended --repository 127.0.0.1 --port 3749 --user "*******" --password "*******" --reregister 1 --agentname "$(hostname)" ;
	else
		cd / ;
		echo '*******' | sudo -S ./ctagent_e_setup_linux_x64_04010000_16954_20200514.run --mode unattended --repository 127.0.0.1 --port 3749 --user "test" --password "password" --reregister 1 --agentname "$(hostname)" ;
	fi
	#cd /opt/Cimcor/CimTrak/CimTrakAgent/ ; echo '280816Ll' | sudo -S ./CimTrakAgentuninstall &> /dev/null ;
	#cd .. ; echo '280816Ll' | sudo -S rm -rf CimTrakAgent/ ;
	#echo "Agent uninstallation now done" ;
	#echo "Agent is installing now" ; 
	#cd / ; echo '280816Ll' | sudo -S ./ctagent_e_setup_linux_x64_04010000_16954_20200514.run --mode unattended --repository 127.0.0.1 --port 3749 --user "user" --password "*********" --reregister 1 --agentname "$(hostname)" ;
t
	echo "Agent is done"
	exit

fi

##steppings
